<?php

namespace App\Console\Commands;

use App\Models\Agreement;
use App\Models\User;
use Illuminate\Console\Command;
use Illuminate\Support\Str;

/**
 * Provision (or reset) a partner login for the new Filament partner panel.
 *
 *   php artisan partner:create-user
 *       --agreement-id=2
 *       --email=ceo@axa.fr
 *       [--name="Martin Leroy"]
 *       [--password=AutoGenerated]
 *
 * The user is linked to the agreement's partner_firebase_id so the panel's
 * PartnerScopedQuery trait auto-filters every resource to their data.
 */
class CreatePartnerUser extends Command
{
    protected $signature = 'partner:create-user
        {--agreement-id= : Existing agreements.id (the partner company)}
        {--email= : Email the partner will use to log in}
        {--name= : Display name (defaults to the agreement partner_name)}
        {--password= : Plain password (auto-generated if omitted)}';

    protected $description = 'Create or reset a partner login for the Filament partner panel';

    public function handle(): int
    {
        $agreementId = $this->option('agreement-id');
        $email = $this->option('email');
        if (!$agreementId || !$email) {
            $this->error('--agreement-id and --email are required');
            return 1;
        }

        $agreement = Agreement::find($agreementId);
        if (!$agreement) {
            $this->error("Agreement #{$agreementId} not found");
            return 1;
        }

        $password = $this->option('password') ?: Str::random(20);

        $user = User::updateOrCreate(
            ['email' => $email],
            [
                'name' => $this->option('name') ?: $agreement->partner_name,
                'password' => bcrypt($password),
                'role' => User::ROLE_PARTNER,
                'partner_firebase_id' => $agreement->partner_firebase_id,
                'is_active' => true,
                'email_verified_at' => now(),
            ]
        );

        $this->newLine();
        $this->info('=== Partner login provisioned ===');
        $this->line('Agreement : <fg=yellow>#' . $agreement->id . ' ' . $agreement->partner_name . '</>');
        $this->line('User ID   : <fg=yellow>' . $user->id . '</>');
        $this->line('Email     : <fg=yellow>' . $user->email . '</>');
        $this->line('Password  : <fg=green;options=bold>' . $password . '</>');
        $this->line('Role      : <fg=yellow>partner</>');
        $this->line('Scope     : <fg=yellow>' . $agreement->partner_firebase_id . '</>');
        $this->newLine();
        $this->line('Login URL : <fg=cyan>https://partner-engine.sos-expat.com/login</>');
        $this->newLine();
        $this->warn('>>> Save the password now — it is hashed immediately and cannot be recovered.');
        $this->newLine();

        return 0;
    }
}
