<?php

namespace App\Filament\Partner\Resources;

use App\Filament\Partner\Concerns\PartnerScopedQuery;
use App\Filament\Partner\Resources\PartnerInvoiceResource\Pages;
use App\Models\PartnerInvoice;
use Filament\Infolists;
use Filament\Infolists\Infolist;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;

/**
 * Read-only view of the partner's own monthly SOS-Call invoices.
 *
 * The partner cannot create or delete invoices — those are generated by
 * the SOS-Expat admin from the main admin panel every month.
 */
class PartnerInvoiceResource extends Resource
{
    use PartnerScopedQuery;

    protected static ?string $model = PartnerInvoice::class;

    protected static ?string $navigationIcon = 'heroicon-o-banknotes';
    protected static ?string $navigationGroup = 'Facturation';
    protected static ?string $navigationLabel = 'Mes factures';
    protected static ?string $modelLabel = 'Facture';
    protected static ?string $pluralModelLabel = 'Factures';
    protected static ?int $navigationSort = 1;

    public static function canCreate(): bool { return false; }
    public static function canEdit($record): bool { return false; }
    public static function canDelete($record): bool { return false; }

    /**
     * Show a red badge on the sidebar when there are overdue invoices,
     * amber for pending, nothing when everything is paid.
     */
    public static function getNavigationBadge(): ?string
    {
        $user = auth()->user();
        if (!$user?->partner_firebase_id) return null;
        $count = PartnerInvoice::where('partner_firebase_id', $user->partner_firebase_id)
            ->whereIn('status', ['pending', 'overdue'])
            ->count();
        return $count > 0 ? (string) $count : null;
    }

    public static function getNavigationBadgeColor(): ?string
    {
        $user = auth()->user();
        if (!$user?->partner_firebase_id) return null;
        $hasOverdue = PartnerInvoice::where('partner_firebase_id', $user->partner_firebase_id)
            ->where('status', 'overdue')
            ->exists();
        return $hasOverdue ? 'danger' : 'warning';
    }

    protected static ?string $recordTitleAttribute = 'invoice_number';

    public static function getGloballySearchableAttributes(): array
    {
        return ['invoice_number', 'period'];
    }

    public static function infolist(Infolist $infolist): Infolist
    {
        return $infolist->schema([
            Infolists\Components\Section::make('Facture ' . '')
                ->schema([
                    Infolists\Components\TextEntry::make('invoice_number')->label('N° facture'),
                    Infolists\Components\TextEntry::make('period')->label('Période'),
                    Infolists\Components\TextEntry::make('active_subscribers')->label('Clients actifs sur la période'),
                    Infolists\Components\TextEntry::make('billing_rate')
                        ->label('Tarif par client')
                        ->money(fn($record) => $record->billing_currency ?? 'EUR'),
                    Infolists\Components\TextEntry::make('total_amount')
                        ->label('Montant total')
                        ->money(fn($record) => $record->billing_currency ?? 'EUR')
                        ->weight('bold')
                        ->size('lg'),
                    Infolists\Components\TextEntry::make('status')
                        ->label('Statut')
                        ->badge()
                        ->color(fn(string $state) => [
                            'paid' => 'success',
                            'pending' => 'warning',
                            'overdue' => 'danger',
                            'cancelled' => 'gray',
                        ][$state] ?? 'gray')
                        ->formatStateUsing(fn(string $state) => [
                            'paid' => 'Payée',
                            'pending' => 'En attente',
                            'overdue' => 'En retard',
                            'cancelled' => 'Annulée',
                        ][$state] ?? $state),
                    Infolists\Components\TextEntry::make('due_date')->label('Échéance')->date(),
                    Infolists\Components\TextEntry::make('paid_at')->label('Payée le')->dateTime()->placeholder('—'),
                    Infolists\Components\TextEntry::make('paid_via')->label('Moyen de paiement')->placeholder('—'),
                ])
                ->columns(2),

            Infolists\Components\Section::make('Détail consommation')
                ->schema([
                    Infolists\Components\TextEntry::make('calls_expert')->label('Appels Expert expat'),
                    Infolists\Components\TextEntry::make('calls_lawyer')->label('Appels Avocat local'),
                ])
                ->columns(2),
        ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('period')
                    ->label('Période')
                    ->sortable()
                    ->formatStateUsing(function ($state) {
                        if (!$state) return '—';
                        [$year, $month] = explode('-', $state);
                        $months = ['','Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Août','Septembre','Octobre','Novembre','Décembre'];
                        return ($months[(int)$month] ?? $month) . ' ' . $year;
                    }),
                Tables\Columns\TextColumn::make('invoice_number')
                    ->label('N°')
                    ->fontFamily('mono')
                    ->copyable()
                    ->toggleable(isToggledHiddenByDefault: true),
                Tables\Columns\TextColumn::make('active_subscribers')
                    ->label('Clients')
                    ->badge()
                    ->color('info'),
                Tables\Columns\TextColumn::make('total_amount')
                    ->label('Montant')
                    ->money(fn($record) => $record->billing_currency ?? 'EUR')
                    ->weight('bold')
                    ->sortable(),
                Tables\Columns\BadgeColumn::make('status')
                    ->label('Statut')
                    ->colors([
                        'success' => 'paid',
                        'warning' => 'pending',
                        'danger' => 'overdue',
                        'gray' => 'cancelled',
                    ])
                    ->formatStateUsing(fn(string $state) => [
                        'paid' => 'Payée',
                        'pending' => 'En attente',
                        'overdue' => 'En retard',
                        'cancelled' => 'Annulée',
                    ][$state] ?? $state),
                Tables\Columns\TextColumn::make('due_date')
                    ->label('Échéance')
                    ->date()
                    ->sortable(),
                Tables\Columns\TextColumn::make('paid_at')
                    ->label('Payée le')
                    ->date()
                    ->placeholder('—')
                    ->toggleable(),
            ])
            ->defaultSort('period', 'desc')
            ->filters([
                Tables\Filters\SelectFilter::make('status')
                    ->label('Statut')
                    ->options([
                        'paid' => 'Payée',
                        'pending' => 'En attente',
                        'overdue' => 'En retard',
                        'cancelled' => 'Annulée',
                    ]),
            ])
            ->actions([
                Tables\Actions\ViewAction::make()->label('Détail'),
                Tables\Actions\Action::make('pdf')
                    ->label('PDF')
                    ->icon('heroicon-o-document-arrow-down')
                    ->color('gray')
                    ->visible(fn($record) => !empty($record->pdf_path))
                    ->url(fn($record) => '/api/partner/sos-call/invoices/' . $record->id . '/pdf', shouldOpenInNewTab: true),
                Tables\Actions\Action::make('payOnline')
                    ->label('Payer en ligne')
                    ->icon('heroicon-o-credit-card')
                    ->color('success')
                    ->visible(fn($record) => $record->status === 'pending' && !empty($record->stripe_hosted_url))
                    ->url(fn($record) => $record->stripe_hosted_url, shouldOpenInNewTab: true),
            ]);
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListPartnerInvoices::route('/'),
            'view'  => Pages\ViewPartnerInvoice::route('/{record}'),
        ];
    }
}
